[versions]
androidx-activity = "1.12.2"
androidx-appcompat = "1.7.1"
androidx-coordinatorlayout = "1.3.0"
androidx-core = "1.17.0"
androidx-fragment = "1.8.9"
androidx-recyclerview = "1.4.0"
androidx-test-core = "1.7.0"
androidx-test-ext-junit = "1.3.0"
com-android-tools-build-gradle = "9.0.0"
com-google-android-material = "1.13.0"
com-kfaraj-support-appcompat = "5.0.4-SNAPSHOT"
com-kfaraj-support-recyclerview = "4.1.1-SNAPSHOT"
junit = "4.13.2"
org-jetbrains-kotlin = "2.3.0"
org-robolectric = "4.16.1"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "androidx-coordinatorlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx-recyclerview" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext-junit" }
com-google-android-material = { module = "com.google.android.material:material", version.ref = "com-google-android-material" }
com-kfaraj-support-appcompat = { module = "com.kfaraj.support.appcompat:appcompat", version.ref = "com-kfaraj-support-appcompat" }
com-kfaraj-support-recyclerview = { module = "com.kfaraj.support.recyclerview:recyclerview", version.ref = "com-kfaraj-support-recyclerview" }
junit = { module = "junit:junit", version.ref = "junit" }
org-robolectric = { module = "org.robolectric:robolectric", version.ref = "org-robolectric" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-tools-build-gradle" }
com-android-library = { id = "com.android.library", version.ref = "com-android-tools-build-gradle" }
com-kfaraj-support-publish = { id = "com.kfaraj.support.publish" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
